# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9229df593e70aa8b9d26bc910bf08c32a1fa42490f9fe9f9613c89adf74b62034c9a6c98f435675e9c8edbca2a87afe759a9f76f549f592974622fb8901d99ad

test:
  secret_key_base: 5f3141307753f93f6b3fe8f00cde106d2bf77b1dd24a0b3743ce9f1deae6dbfa9414b1a2cc9007e62fe9d7aed8deb1a97f7a22ccf3e34d5912d728175173f756

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
